[package]
name = "rolex"
version = "0.1.0"
authors = ["Alex Kucherenko <kucherenko.email@gmail.com>"]
edition = "2018"
description = "A CLI utility for managing server tasks"
license = "MIT"

[dependencies]
clap = "2.33.3"

[build-dependencies]
